name: Test Project
on: 
  push: 
    branches:
      - main
    # paths-ignore:
    #   - '.github/workflows/*'
  workflow_dispatch:
jobs: 
  identify-affected:
    runs-on: ubuntu-latest
    outputs: 
      affected: ${{ steps.set-affected-output.outputs.affected }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Install Nodejs
        uses: actions/setup-node@v3
        with: 
          node-version: 18.16.0
      - name: Identify affected projects
        id: "set-affected-output"
        run: |
            affected="Hello World"
            echo "Output [$affected]"
            echo "affected=$affected" >> $GITHUB_OUTPUT
  my_second_job:
    needs: identify-affected
    runs-on: ubuntu-latest
    steps:
      - run: echo affected [${{needs.set-affected-output.outputs.affected}}]