name: Test Project
on: 
  push: 
    branches:
      - main
    # paths-ignore:
    #   - '.github/workflows/*'
  workflow_dispatch:
jobs: 
  identify-affected:
    runs-on: ubuntu-latest
    outputs: 
      affected: ${{ steps.set-affected-output.outputs }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Install Nodejs
        uses: actions/setup-node@v3
        with: 
          node-version: 18.16.0
      - name: Identify affected projects
        run: |
            my_var="Hello World"
            echo "Output [$my_var]"
            echo "my_var=$my_var" >> $GITHUB_OUTPUT