name: Test Project
on: 
  push: 
    branches:
      - dev
    # paths-ignore:
    #   - '.github/workflows/*'
  workflow_dispatch:
jobs: 
  identify-affected:
    runs-on: ubuntu-latest
    outputs: 
      affected: ${{ steps.set-affected-output.outputs.test }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Install Nodejs
        uses: actions/setup-node@v3
        with: 
          node-version: 18.16.0
      - name: Install nx
        run: npm install -g nx
      - name: Identify affected projects
        id: set-affected-output
        run: echo "test=world" >> "$GITHUB_OUTPUT"
  test: 
    runs-on: ubuntu-latest
    needs: identify-affected
    steps:
      - env:
          OUTPUT1: ${{needs.identify-affected.outputs.affected}}
        run: |
          my_var="Hello World"
          echo "Output $my_var"
          echo "$OUTPUT1"