name: Test Project
on: 
  push: 
    branches:
      - main
    # paths-ignore:
    #   - '.github/workflows/*'
  workflow_dispatch:
jobs: 
  identify-affected:
    runs-on: ubuntu-latest
    outputs: 
      affected: ${{ steps.set-affected-output.outputs }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Install Nodejs
        uses: actions/setup-node@v3
        with: 
          node-version: 18.16.0
      - name: Install nx
        run: npm install -g nx
      - name: Identify affected projects
        id: set-affected-output
        run: |
          my_var="Hello World"
          echo "echo '::set-output name=affected::${{$my_var}}' ';'

  # test: 
  #   runs-on: ubuntu-latest
  #   steps: 
  #     - name: Checkout Code
  #       uses: actions/checkout@v4
  #     - name: Install Nodejs
  #       uses: actions/setup-node@v3
  #       with: 
  #         node-version: 18.16.0
  #     - name: Install dependencies
  #       run: npm ci